# Generated by Django 6.0.3 on 2026-03-22 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_enrollment_date_enrolled_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(default='http://github.com'),
        ),
    ]
